---
tungchiahui_compose_project_name: tungchiahui-production
tungchiahui_config_root: /etc/tungchiahui
tungchiahui_content_polling_enabled: "false"
tungchiahui_data_root: /var/lib/tungchiahui
tungchiahui_deployment_sha: ""
tungchiahui_install_packages: true
tungchiahui_manage_stack: true
tungchiahui_origin_port: "8443"
tungchiahui_repository_root: "{{ playbook_dir }}/../../../.."
tungchiahui_runtime_group_gid: 10050
tungchiahui_secret_file: ""
tungchiahui_secret_root: /run/tungchiahui/secrets
tungchiahui_search_polling_enabled: "false"
tungchiahui_service_image: ""
tungchiahui_web_image: ""
