services:
  postgres:
    ports:
      - "127.0.0.1::5432"
  pgbouncer:
    ports:
      - "127.0.0.1::6432"
  s3mock:
    environment:
      COM_ADOBE_TESTING_S3MOCK_STORE_RETAIN_FILES_ON_EXIT: "false"
    ports:
      - "127.0.0.1::9090"
  control-api:
    ports:
      - "127.0.0.1::8080"
  fake-deploy-agent:
    ports:
      - "127.0.0.1::8081"
  web:
    ports:
      - "127.0.0.1::3000"
